# Site settings
title: "Phong + Hue"
description: |
    San Ramon, California

    October 7, 2018
owner: Vi Ho Phong
first_published: 2018
email: vihophong@live.com
baseurl: "/weddingsite" # the subpath of your site, e.g. /blog
url: "phongandhue.github.io" # the base hostname & protocol for your site

social:
  github: https://github.com/phongandhue/weddingsite.git

# Build settings
markdown: kramdown
